# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
# permalink: /:categories/:year/:month/:day/:title 
permalink: /blog/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", 'lib', 'spec']
pygments: true
markdown: redcarpet
# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : 里克的自习室
tagline: Site Tagline
blog_url: http://railser.cn
author :
  name : 里克
  intro: 'Rails Soho Developer, Blog Writer, focus on OpenERP recently.'
  email : hi@liwei.me
  github : liwei78
  twitter : liwei78
  feedburner : liwei78
  rubychina_name : liwei78
  qq : '5175486'
  skype : railsercn
  weixin_pic: '/assets/themes/the-program/skin/weixin.jpg'

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://railser.cn


