permalink: /blog/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", 'lib', 'spec', 'tool']

pygments: true
markdown: redcarpet

paginate: 16 # pagination based on number of posts
# paginate_path: "page:num"

title : 里克的自习室
blog_url: http://railser.cn
author :
  name : 里克
  intro: 'Rails Soho Developer, Blog Writer, focus on OpenERP recently.'
  email : hi@liwei.me
  github : liwei78
  twitter : liwei78
  feedburner : liwei78
  rubychina : liwei78
  qq : '5175486'
  skype : railsercn
  weixin_pic: '/assets/themes/the-program/skin/weixin.jpg'



