permalink: /blog/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", 'lib', 'spec', 'tool']

pygments: true
markdown: redcarpet

paginate: 10 # pagination based on number of posts
# paginate_path: "page:num"

title : 里克的自习室
description: "Ruby和Rails的开发笔记，里克的翻译及原创作品。"
keywords: "Ruby,Rails,soho,develop,笔记,经验,翻译,原创"
blog_url: http://railser.cn
author :
  name : 里克
  intro: 'Rails Soho Developer, Blog Writer, focus on OpenERP recently.'
  email : hi@liwei.me
  github : liwei78
  twitter : liwei78
  feedburner : liwei78
  rubychina : liwei78
  qq : '5175486'
  skype : guxing203


links:
  - title: 首页
    url: /
  - title: 分类
    url: /categories.html
  - title: Tags
    url: /tags.html


production_url: http://railser.cn
assets_url: http://railser.cn
