permalink: /blog/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", 'lib', 'spec', 'tool']

pygments: true
markdown: redcarpet

paginate: 10 # pagination based on number of posts
# paginate_path: "page:num"

title : 里克的自习室
description: "写给自己的技术笔记"
keywords: "ruby,rails,soho,翻译,原创"
blog_url: http://railser.cn
author :
  name : 里克
  intro: 'SOHO developer, blog writer.'
  email : hi@liwei.me
  github : liwei78
  twitter : liwei78
  feedburner : liwei78
  rubychina : liwei78
  qq : '5175486'
  skype : guxing203

links:
  - title: 首页
    url: /
  - title: 分类
    url: /categories.html
  - title: Tags
    url: /tags.html

production_url: http://railser.cn
assets_url: http://railser.cn
